name: Deployflow for testing on EC2 machine

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: SSH setup and  keyscan
        run: |
          mkdir -p ~/.ssh

          echo "${{secrets.SSH_DEMOKEY}}" > ~/.ssh/MyPrivateKey
          chmod 400 ~/.ssh/MyPrivateKey

          ssh-keyscan -H ${{secrets.EC2_IP_TEST}} >> ~/.ssh/known_hosts

      - name: copy index.html file for nginx
        run: |
          ssh-keyscan -H ${{secrets.EC2_IP_TEST}} >> ~/.ssh/known_hosts
          ssh -i ~/.ssh/MyPrivateKey ubuntu@${{secrets.EC2_IP_TEST}} "mkdir -p /home/ubuntu/frontend/"
          scp -i ~/.ssh/MyPrivateKey frontend/* ubuntu@${{secrets.EC2_IP_TEST}}:/home/ubuntu/frontend/
          ssh -i ~/.ssh/MyPrivateKey ubuntu@${{secrets.EC2_IP_TEST}} "sudo cp -r /home/ubuntu/frontend  /var/www/html/"
