name: Deployflow

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh

          echo "${{secrets.SSH_ACTION_DEMO_KEY}}" > ~/.ssh/MyPrivateKey
          chmod 400 ~/.ssh/MyPrivateKey
           
          ssh-keyscan -H "${{secrets.EC2_IP}}" >> ~/.ssh/known_hosts
      - name: copy files
        run: |
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP}}" "mkdir -p ~/frontend"
          scp -i ~/.ssh/MyPrivateKey frontend/* ubuntu@${{secrets.EC2_IP}}:~/frontend
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP}}" "docker build -t myfrontend /home/ubuntu/frontend"

# Dateien rüberkopieren → Image auf EC2 bauen → Container starten).
