name: Deployflow

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5

      - name: SSH setup
        run: |
          mkdir -p ~/.ssh

          echo "${{secrets.SSH_DEMOKEY}}" > ~/.ssh/MyPrivateKey
          chmod 400 ~/.ssh/MyPrivateKey

      - name: SSH key scan
        run: |
          ssh-keyscan -H "${{secrets.EC2_IP_1}}" >> ~/.ssh/known_hosts
          ssh-keyscan -H "${{secrets.EC2_IP_2}}" >> ~/.ssh/known_hosts

      - name: copy-data
        run: |
          scp -i ~/.ssh/MyPrivateKey index.html ubuntu@"${{secrets.EC2_IP_1}}":/home/ubuntu/index.html
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP_1}}" "sudo cp /home/ubuntu/index.html  /var/www/html/index.html"
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP_1}}" "sudo echo '<br>$(hostname)' >>  /var/www/html/index.html"

          scp -i ~/.ssh/MyPrivateKey index.html ubuntu@"${{secrets.EC2_IP_2}}":/home/ubuntu/index.html
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP_2}}" "sudo cp /home/ubuntu/index.html  /var/www/html/index.html"
          ssh -i ~/.ssh/MyPrivateKey ubuntu@"${{secrets.EC2_IP_2}}" "sudo echo '<br>$(hostname)' >>  /var/www/html/index.html"
